# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yummy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yummy
  pod 'IBMWatsonAssistantV1', '~> 3.5.1'
    pod 'IBMWatsonAssistantV2', '~> 3.5.1'
    pod 'IBMWatsonNaturalLanguageUnderstandingV1', '~> 3.5.1'
end
